### PR TITLE
[14.0][MIG] connector_importer [WIP]

### PR DESCRIPTION
**Pull request by kittiu**
Standard Migration, work in process.

Dependencies:

- [x] connector https://github.com/OCA/connector/pull/385

### CODE REVIEW

**Comment by kittiu** [comment]
I got following error when installing,

```
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 232, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 581, in _build_model
    ModelClass.__bases__ = tuple(bases)
```

@simahawk 
I only can fix it by remove `JobRelatedMixin`, from `class ImportRecordset(models.Model, JobRelatedMixin):`. if you know why?

Just wondering, why not include fields and function ob JobRelatedMixin in `import.source.consumer.mixin`

**Comment by simahawk** [comment]
> I got following error when installing,
> 
> ```
>   File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 232, in load
>     model = cls._build_model(self, cr)
>   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 581, in _build_model
>     ModelClass.__bases__ = tuple(bases)
> ```
> 
> @simahawk
> I only can fix it by remove `JobRelatedMixin`, from `class ImportRecordset(models.Model, JobRelatedMixin):`. if you know why?
> 
> Just wondering, why not include fields and function ob JobRelatedMixin in `import.source.consumer.mixin`

the job mixin has nothing to deal w/ the source. It has been done like that because w/ an odoo mixin I had issues.
Now, this was happening ages ago, and maybe today it just works. Can you open a PR for v13 to change only this?

**Comment by kittiu** [comment]
@simahawk OK

**Comment by ps-tubtim** [comment]
@kittiu I change class JobRelatedMixin  from object to abstract model because resolving the error when installing this module.

**Comment by hailangvn** [comment]
Good day @simahawk, I will take over this PR. Per your advise, @ps-tubtim's change is backported to 13.0 at https://github.com/OCA/connector-interfaces/pull/81.

Thanks @kittiu and @ps-tubtim for your work.

**Comment by kittiu** [comment]
> Good day @simahawk, I will take over this PR. Per your advise, @ps-tubtim's change is backported to 13.0 at #81.
> 
> Thanks @kittiu and @ps-tubtim for your work.

🙏 Thanks.
Sorry we really don't have time for this now.

**Comment by simahawk** [comment]
I took it over here to speed it up and fix some other small issues https://github.com/OCA/connector-interfaces/pull/82

**Pull request closed without merging**
