### PR TITLE
[14.0] connector_importer + connector_importer_product: misc fix/imp

### PR DESCRIPTION
**Pull request by simahawk**
See atomic commits for details.

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
That RecordCapturer backport is not used, finally, is it? 🤔

**Comment by simahawk** [comment]
> That RecordCapturer backport is not used, finally, is it? thinking



> That RecordCapturer backport is not used, finally, is it? thinking

That's a funny story... I don't know where the code that uses it has gone :sweat_smile:

**Comment by simahawk** [comment]
Ok, the funny thing is that it is used already in [14.0 branch](https://github.com/OCA/connector-interfaces/blob/14.0/connector_importer_product/tests/test_product_packaging.py#L7) and  but I guess tests didn't fail due to the GH actions outage :shrug:
It seems I lost the commit here on this PR https://github.com/OCA/connector-interfaces/pull/109

**Pull request merged**
