### PR TITLE
[ADD] auditlog_async

### PR DESCRIPTION
**Pull request by hbrunn**
Audit Log (asynchronous)
========================

This module was written to allow to configure asynchronous logging rules. 

Installation
============

To install this module, you need to:

- have a working [connector](http://odoo-connector.com) configuration

Configuration
=============

To configure this module, you need to:

- go to your audit log rules
- check the box 'Asynchronous' on a rule
- most of the rule processing will happen asynchronously now

Known issues / Roadmap
======================

* note that this can cause the logs to be slightly off in case there have been transactions between the transaction of the original method call and the logging call. That's pretty much immanent of aynchronicity, so use this option only of this is an acceptable tradeoff for your use case

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
code LGTM

**Comment by sebalix** [comment]
@hbrunn do you have some benchmark about this module?
My first attempt to make auditlog async was not very successful (https://github.com/OCA/server-tools/pull/173), but I was using delay instead of a SQL query to create the job.

**Comment by hbrunn** [comment]
using sql did all the difference there. In my case the difference is huge, but that's caused by a cascade of models which have logging turned on. For say just logging res.partner writes, the difference won't be very impressing (but visible)

**Review by sebalix — APPROVED** [review]

**Comment by nadiaafa** [comment]
@hbrunn thank you very much for the module.
I would like to continue on it because i need it on our big project, actually we have a problem sometimes when validating invoices, it takes too long, we use audit rules on many objects so i would like to improve the performance by running audit logs in jobs and continue on your module by changing the creation date of the log to the date of job creation and migrate it to v11 so that i can use it and publish it as well.
I would like also to know if you have other ideas about how to improve odoo performance when validating an invoice/ generating entries.
@ simahawk and @sebalix will this module be merged soon or need more work to do? 
Thank you Guys for your efforts.

**Comment by hbrunn** [comment]
what's blocking for merge here is the missing tests, if you add them in your version, I'll happily backport them

**Comment by nadiaafa** [comment]
@hbrunn i will add them, thank you.

**Pull request closed without merging**
