### PR TITLE
Update base_import_async.py

### PR DESCRIPTION
**Pull request by OdooMod**
fix error,python csv "delimiter" must be string, not unicode

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:  LGTM

**Comment by rvalyi** [comment]
@waveyeung well the code looks ok, but you should sign the OCA CLA and ensure the email address you use for it is registered in your Github account.

**Comment by lmignon** [comment]
@waveyeung Is your fix really for 9.0? This module is un ported in 9.0 so I presume that your fix target the 8.0 branch.

**Comment by OdooMod** [comment]
@lmignon Yes,my envirnment is 8.0. This error came from python's csv module, so this fix will also improve the project.

**Comment by lmignon** [comment]
@waveyeung Your PR target the 9.0 branch.

>  Open waveyeung  wants to merge 2 commits into OCA:9.0 from waveyeung:patch-1

Can you do a new PR on 8.0?

**Comment by OdooMod** [comment]
@lmignon Okay

**Comment by OdooMod** [comment]
@rvalyi Thanks,I had sign in the http://odoo-community.org with [odoo.com] account, and my account email was not activated at that time. I have no idea about the reason.

**Comment by lmignon** [comment]
superseded by #24

**Pull request closed without merging**
