### PR TITLE
[FIX] connector_importer: guess the CSV encoding when generating the report

### PR DESCRIPTION
**Pull request by Tonow-c2c**
idem as https://github.com/OCA/connector-interfaces/pull/66 but for v `13.0`

ping @sebalix

### CODE REVIEW

**Review by jcoux — APPROVED** [review]
Seems good, no test

**Review by sebalix — APPROVED** [review]

**Comment by simahawk** [comment]
@Tonow-c2c this is merging https://github.com/OCA/connector-interfaces/pull/68 as soon as it's done, pls rebase and we can merge this too. Thanks!

**Comment by pedrobaeza** [comment]
@simahawk ocabot stuck on merge

**Pull request merged**
